version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  web:
    build: .
    command: /usr/local/heroku/bin/heroku local
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/milieu/:rw
