postgres:
  image: postgres
  ports:
    - '5432:5432'

web:
  build: .
  command: bash -c "rake db:create && rake db:migrate && npm install && foreman start"
  volumes:
    - .:/m-server
  ports:
    - '3000:3000'
  links:
    - postgres