default: &default
  adapter: postgresql
  database: milieu
  encoding: unicode
  username: ash
  password: 
  host: localhost

development:
  <<: *default
  port: 5432

test:
  <<: *default

production:
  <<: *default
  port: 5432
