development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 10
  database: ottawa_development
  username: ash
  password:

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 10
  database: ottawa_test
  username: ash
  password:

production:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_STATS_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>
